/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as VerifyTokenIndexRouteImport } from './routes/verify/$token/index'
import { Route as ResetPasswordTokenIndexRouteImport } from './routes/reset-password/$token/index'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenIndexRoute = VerifyTokenIndexRouteImport.update({
  id: '/verify/$token/',
  path: '/verify/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenIndexRoute = ResetPasswordTokenIndexRouteImport.update({
  id: '/reset-password/$token/',
  path: '/reset-password/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/me': typeof MeIndexRoute
  '/register': typeof RegisterIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/reset-password/$token': typeof ResetPasswordTokenIndexRoute
  '/verify/$token': typeof VerifyTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/me': typeof MeIndexRoute
  '/register': typeof RegisterIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/reset-password/$token': typeof ResetPasswordTokenIndexRoute
  '/verify/$token': typeof VerifyTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/': typeof ChatIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/me/': typeof MeIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/reset-password/$token/': typeof ResetPasswordTokenIndexRoute
  '/verify/$token/': typeof VerifyTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/register'
    | '/profile/$userId'
    | '/reset-password/$token'
    | '/verify/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/me'
    | '/register'
    | '/profile/$userId'
    | '/reset-password/$token'
    | '/verify/$token'
  id:
    | '__root__'
    | '/'
    | '/chat/'
    | '/discover/'
    | '/forgot-password/'
    | '/login/'
    | '/me/'
    | '/register/'
    | '/profile/$userId/'
    | '/reset-password/$token/'
    | '/verify/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  ResetPasswordTokenIndexRoute: typeof ResetPasswordTokenIndexRoute
  VerifyTokenIndexRoute: typeof VerifyTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token/': {
      id: '/verify/$token/'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token/': {
      id: '/reset-password/$token/'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MeIndexRoute: MeIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  ResetPasswordTokenIndexRoute: ResetPasswordTokenIndexRoute,
  VerifyTokenIndexRoute: VerifyTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
