import { User, ChatPreview, Notification, FilterState } from "../types";
export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Olivia Mitchell",
    username: "@Oliviamitch",
    age: 28,
    location: "Brooklyn, NY",
    distance: 2.3,
    bio: "Coffee enthusiast ☕ | Digital nomad 🌍 | Always up for a hiking adventure. Looking for someone who can keep up with my travel bug and loves deep conversations over good wine.",
    tags: ["travel", "coffee", "hiking", "yoga", "photography", "vegan"],
    fameRating: 87,
    photos: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1502764613149-7f1d229e230f?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: true,
  },
  {
    id: "2",
    name: "Marcus Chen",
    username: "@marcusc",
    age: 32,
    location: "Manhattan, NY",
    distance: 5.8,
    bio: "Software engineer by day, amateur chef by night 👨‍💻🍳 Seeking someone who appreciates good food, spontaneous road trips, and can handle my terrible puns.",
    tags: ["coding", "cooking", "running", "gaming", "movies", "foodie"],
    fameRating: 72,
    photos: [
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: true,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    username: "@emilyrod",
    age: 26,
    location: "Queens, NY",
    distance: 8.1,
    bio: "Artist 🎨 | Dog mom to Luna 🐕 | Fitness junkie. If you can make me laugh and enjoy brunch as much as I do, we'll get along great!",
    tags: ["art", "fitness", "dogs", "brunch", "music", "dancing"],
    fameRating: 91,
    photos: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400&h=500&fit=crop",
    ],
    isOnline: false,
    lastSeen: "23 minutes ago",
  },
  {
    id: "4",
    name: "David Kim",
    username: "@davidkim",
    age: 30,
    location: "San Francisco, CA",
    distance: 3.5,
    bio: "Tech entrepreneur 🚀 | Marathon runner 🏃 | Always chasing the next adventure. Looking for someone curious and ambitious.",
    tags: ["tech", "running", "startups", "travel", "coffee"],
    fameRating: 80,
    photos: [
      "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: false,
  },
  {
    id: "5",
    name: "Olivia Brown",
    username: "@oliviab",
    age: 27,
    location: "Los Angeles, CA",
    distance: 4.2,
    bio: "Yoga instructor 🧘‍♀️ | Plant lover 🌿 | Beach trips are my therapy. Swipe right if you love sunsets and deep talks.",
    tags: ["yoga", "plants", "travel", "beach", "wellness"],
    fameRating: 85,
    photos: [
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=500&fit=crop",
    ],
    isOnline: false,
    lastSeen: "1 hour ago",
  },
  {
    id: "6",
    name: "Liam Johnson",
    username: "@liamj",
    age: 29,
    location: "Austin, TX",
    distance: 6.0,
    bio: "Musician 🎸 | BBQ lover 🍖 | Looking for someone to jam with on weekends and explore the city together.",
    tags: ["music", "bbq", "guitar", "hiking", "movies"],
    fameRating: 78,
    photos: [
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: true,
  },
  {
    id: "7",
    name: "Sophia Lee",
    username: "@sophialee",
    age: 25,
    location: "Seattle, WA",
    distance: 2.8,
    bio: "Coffee barista ☕ | Bookworm 📚 | Nature lover. Swipe right if you enjoy quiet mornings and spontaneous hikes.",
    tags: ["coffee", "books", "nature", "photography", "yoga"],
    fameRating: 90,
    photos: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop",
    ],
    isOnline: false,
    lastSeen: "5 minutes ago",
  },
  {
    id: "8",
    name: "Ethan Walker",
    username: "@ethanw",
    age: 31,
    location: "Chicago, IL",
    distance: 7.4,
    bio: "Fitness trainer 💪 | Gamer 🎮 | Always up for a new challenge. Looking for someone active and fun-loving.",
    tags: ["fitness", "gaming", "sports", "travel", "foodie"],
    fameRating: 76,
    photos: [
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: false,
  },
  {
    id: "9",
    name: "Mia Torres",
    username: "@miatorres",
    age: 28,
    location: "Miami, FL",
    distance: 3.9,
    bio: "Beach lover 🏖 | Photographer 📸 | Salsa dancer 💃. Looking for someone who enjoys life to the fullest.",
    tags: ["beach", "photography", "dance", "travel", "music"],
    fameRating: 88,
    photos: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=400&h=500&fit=crop",
    ],
    isOnline: false,
    lastSeen: "30 minutes ago",
  },
  {
    id: "10",
    name: "Noah Martinez",
    username: "@noahm",
    age: 33,
    location: "Denver, CO",
    distance: 5.1,
    bio: "Outdoor enthusiast 🏞 | Coffee lover ☕ | Dog dad 🐶. Seeking someone adventurous and kind-hearted.",
    tags: ["hiking", "coffee", "dogs", "travel", "photography"],
    fameRating: 82,
    photos: [
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=500&fit=crop",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=500&fit=crop",
    ],
    isOnline: true,
    verified: true,
  },
];

export const MOCK_CHATS: ChatPreview[] = [
  {
    userId: "2",
    user: MOCK_USERS[1],
    lastMessage: {
      id: "m1",
      senderId: "2",
      text: "I'm planning to go this weekend if the weather holds up",
      timestamp: "2:34 PM",
      isRead: false,
    },
    unreadCount: 1,
  },
  {
    userId: "3",
    user: MOCK_USERS[2],
    lastMessage: {
      id: "m2",
      senderId: "me",
      text: "That was in Tulum, Mexico. Have you been?",
      timestamp: "2 hours ago",
      isRead: true,
    },
    unreadCount: 0,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: "like",
    actorName: "Marcus Chen",
    actorId: "2",
    timestamp: "5 minutes ago",
    isRead: false,
  },
  {
    id: "2",
    type: "view",
    actorName: "Emily Rodriguez",
    actorId: "3",
    timestamp: "12 minutes ago",
    isRead: false,
  },
  {
    id: "3",
    type: "match",
    actorName: "Olivia Mitchell",
    actorId: "1",
    timestamp: "1 hour ago",
    isRead: true,
  },
];

// Initial filters - null means "not applied" (use API defaults)
export const INITIAL_FILTERS: FilterState = {
  ageRange: null,
  distance: null,
  fameRange: null,
  tags: [],
  sortBy: "distance",
};
